'use client';

import { useState } from 'react';
import { ShieldCheck, X, RefreshCw } from 'lucide-react';
import { toast } from 'sonner';

interface AccessCodeModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess: () => void;
}

export function AccessCodeModal({ isOpen, onClose, onSuccess }: AccessCodeModalProps) {
  const [code, setCode] = useState('');
  const [isVerifying, setIsVerifying] = useState(false);
  const [errorText, setErrorText] = useState<string | null>(null);

  if (!isOpen) return null;

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!code) {
      setErrorText('Access code is required');
      return;
    }
    if (code.length !== 4 || isNaN(Number(code))) {
      setErrorText('Access code must be a 4-digit number');
      return;
    }

    setIsVerifying(true);
    setErrorText(null);
    try {
      const res = await fetch('/api/settings/verify', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ code }),
      });
      const data = await res.json();

      if (data.valid) {
        toast.success(data.message || 'Access granted!');
        onSuccess();
        onClose();
      } else {
        setErrorText(data.message || 'Invalid access code');
        toast.error(data.message || 'Verification failed');
      }
    } catch (err) {
      setErrorText('Network connection failure. Please try again.');
      toast.error('Failed to verify access code');
    } finally {
      setIsVerifying(false);
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const val = e.target.value;
    // Only allow digits and max length of 4
    if (/^\d*$/.test(val) && val.length <= 4) {
      setCode(val);
      setErrorText(null);
    }
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/90 backdrop-blur-md">
      <div 
        className="w-full max-w-sm bg-[#121214] border border-[#1f1f23] rounded-xl p-6 relative overflow-hidden space-y-5 animate-fade-in"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="absolute top-4 right-4">
          <button 
            onClick={onClose} 
            className="p-1 rounded-full text-[#8a8a8e] hover:text-white transition-colors cursor-pointer"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        <div className="flex flex-col items-center text-center space-y-3 pt-2">
          <div className="w-12 h-12 rounded-full bg-[#0071e3]/10 border border-[#0071e3]/20 flex items-center justify-center text-[#2997ff]">
            <ShieldCheck className="w-6 h-6" />
          </div>
          <div className="space-y-1">
            <h3 className="text-sm font-semibold uppercase tracking-wider text-white">Enter Lesson Code</h3>
            <p className="text-xs text-[#8a8a8e] leading-relaxed max-w-[260px]">
              Type the 4-digit exam access code generated by your teacher to launch this test session.
            </p>
          </div>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="space-y-1.5 text-center">
            <input
              type="text"
              pattern="\d*"
              maxLength={4}
              placeholder="0 0 0 0"
              value={code}
              onChange={handleChange}
              disabled={isVerifying}
              className="w-full tracking-[1.5em] text-center font-mono py-3 text-lg bg-black border border-[#1f1f23] rounded-lg text-white focus:outline-none focus:border-[#0071e3] transition-colors"
              autoFocus
              required
            />
            {errorText ? (
              <span className="block text-xs font-semibold text-[#ff453a] pt-1">
                {errorText}
              </span>
            ) : null}
          </div>

          <button
            type="submit"
            disabled={isVerifying || code.length !== 4}
            className="w-full py-2.5 bg-white text-black hover:bg-[#cfcfcf] font-semibold text-xs uppercase tracking-widest rounded-full transition-all cursor-pointer flex items-center justify-center gap-2 disabled:opacity-50"
          >
            {isVerifying ? (
              <>
                <RefreshCw className="w-3.5 h-3.5 animate-spin" /> Verifying...
              </>
            ) : (
              'Verify & Start Exam'
            )}
          </button>
        </form>
      </div>
    </div>
  );
}
